
spring.datasource.url=jdbc:postgresql://localhost:5432/expense_tracker
spring.datasource.username=postgres
spring.datasource.password=vatsal$sharma@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
